name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  matrix_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v

  e2e_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test
        run: go test -tags e2e -v -run TestE2E
